try
  clear a
  a;
catch
  1
end_try_catch
